<a href="https://colab.research.google.com/github/Anusree-Dineshan/DataScience_lab/blob/main/1b_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #importing numpy package

In [2]:
x = np.array([1,2,3,4]) #creating numpy array from list

In [3]:
print(x)


[1 2 3 4]


In [4]:
print(type(x))


<class 'numpy.ndarray'>


In [5]:
y = np.array([[1,2],[3,4]])

In [6]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [7]:
z = np.array([[1+0.j,2+5.j]])  #printing thr dimension of the numpy array

In [8]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [9]:
a = np.zeros((2,3)) #creating numpy array of zeros , of dimension (2,3)

In [10]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(a.shape)

(2, 3)


In [12]:
b = np.ones((2,3), dtype=int) #creating numpy array of ones , of dimension (2,3) and integer type

In [13]:
print(b)

[[1 1 1]
 [1 1 1]]


In [14]:
d = np.eye(3) ## identity matrix

In [15]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
e = np.arange(10) ##similar to Range function

In [17]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
e = np.arange(12, 21)

In [19]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [20]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [21]:
f = np.linspace(1,20,7) ## It create intervals

In [22]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [23]:
g = np.random.random((3,4))

In [24]:
print(g)

[[0.40707979 0.69908966 0.61066481 0.94047937]
 [0.30283301 0.11933008 0.2612927  0.83066394]
 [0.17389844 0.21123376 0.3961251  0.61510694]]
